# Generated by Django 6.0.7 on 2026-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default='2026-07-10 10:00:00+00', verbose_name='Дата обновления'),
        ),
    ]
